# Generated by Django 4.0.4 on 2022-05-29 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('short', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clips',
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='Urlroot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('short', models.CharField(max_length=10, unique=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, default='', max_length=200)),
                ('clip_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clip')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'urlroot',
                'ordering': ['published'],
            },
        ),
    ]
