# Generated by Django 4.0.4 on 2022-05-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlroot',
            name='clip_id',
        ),
        migrations.DeleteModel(
            name='Clip',
        ),
    ]
